baseURL = "https://kawhing.github.io/"
title = "kawhing's Blog"
theme = "PaperMod"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Posts"
        url = "/en/posts"
        weight = 1

  [languages.zh]
    languageName = "中文"
    weight = 2
    contentDir = "content/zh"
    [languages.zh.menu]
      [[languages.zh.menu.main]]
        name = "文章"
        url = "/zh/posts/"
        weight = 1

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true